# Generated by Django 4.0.4 on 2022-05-15 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10, null=True)),
                ('income', models.CharField(max_length=100, null=True)),
                ('region', models.CharField(max_length=50, null=True)),
                ('marital_status', models.IntegerField(choices=[('1', 'Married'), ('0', 'Unmarried')], default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_id', models.IntegerField(unique=True)),
                ('date_of_purchase', models.DateField(blank=True, null=True)),
                ('fuel', models.CharField(max_length=20, null=True)),
                ('vehicle_segment', models.CharField(max_length=2, null=True)),
                ('premium', models.IntegerField()),
                ('injury_liability', models.IntegerField(default=0)),
                ('injury_protection', models.IntegerField(default=0)),
                ('damage_liability', models.IntegerField(default=0)),
                ('collision', models.IntegerField(default=0)),
                ('comprehensive', models.IntegerField(default=0)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CustomerInsurance.customer')),
            ],
        ),
    ]
