# Generated by Django 4.0.4 on 2022-05-15 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerInsurance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='income',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='region',
        ),
        migrations.AddField(
            model_name='policy',
            name='income',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='policy',
            name='region',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
