# Generated by Django 4.0.4 on 2022-05-15 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerInsurance', '0002_remove_customer_income_remove_customer_region_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='marital_status',
        ),
        migrations.RemoveField(
            model_name='policy',
            name='region',
        ),
        migrations.AddField(
            model_name='customer',
            name='region',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='policy',
            name='marital_status',
            field=models.IntegerField(choices=[('1', 'Married'), ('0', 'Unmarried')], default=0, null=True),
        ),
    ]
