# Generated by Django 4.0.4 on 2022-05-15 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerInsurance', '0003_remove_customer_marital_status_remove_policy_region_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='date_of_purchase',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
