# Generated by Django 4.0.4 on 2022-05-15 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerInsurance', '0004_alter_policy_date_of_purchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='customer_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CustomerInsurance.customer'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='date_of_purchase',
            field=models.DateField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='policy',
            name='policy_id',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='policy',
            name='premium',
            field=models.IntegerField(null=True),
        ),
    ]
